version: '3.8'
services:
  postgres-db:
    image: postgres:14
    container_name: shop-db
    restart: always
    ports:
      - 5430:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop-db
    networks:
      - tenderi

networks:
  tenderi:
    driver: bridge